name: sanal_lira
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.1.beta <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  google_fonts: ^3.0.1
  http: ^0.13.5
  provider: ^6.0.5
  simple_animations: ^5.0.0+3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
